version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb+srv://abhishekmohan7171:g7N4GddJEso309n4@aws-s3-scs.9yda4vu.mongodb.net/?retryWrites=true&w=majority&appName=aws-s3-scs
      - JWT_SECRET=sdfqernkj435698hsgsk
      - FILE_UPLOAD_PATH=/usr/src/app/uploads
    volumes:
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: